export const majors = [
  "Computer Science",
  "Computer Science + Advertising",
  "Computer Science + Animal Sciences",
  "Computer Science + Anthropology",
  "Computer Science + Astronomy",
  "Computer Science + Bioengineering",
  "Computer Science + Chemistry",
  "Computer Science + Crop Sciences",
  "Computer Science + Economics",
  "Computer Science + Education",
  "Computer Science + Geography & Geographic Information Science",
  "Computer Science + Linguistics",
  "Computer Science + Music",
  "Computer Science + Philosophy",
  "Computer Science + Physics",
  "Computer Engineering",
  "Data Science",
  "ACES Undeclared",
  "Accountancy",
  "Accountancy + Data Science",
  "Accountancy Analytics",
  "Accountancy Data Analytics",
  "Accounting Foundations",
  "Acting",
  "Actuarial Science",
  "Adult Development",
  "Advanced Analytics",
  "Advanced Clinical Practice",
  "Advanced Design Thinking",
  "Advertising",
  "Aerospace Engineering",
  "Aerospace Systems Engineering",
  "African American Studies",
  "African Studies",
  "Aging",
  "Agri-Accounting",
  "Agribusiness Markets & Management",
  "Agribusiness and Sustainable Food Production Economics",
  "Agricultural & Applied Economics",
  "Agricultural & Biological Engineering",
  "Agricultural & Biological Engineering Sciences",
  "Agricultural & Consumer Economics",
  "Agricultural Communications",
  "Agricultural Leadership, Education, & Communications",
  "Agricultural Production & Processing",
  "Agroecology",
  "Agronomy",
  "American Indian & Indigenous Studies",
  "American Indian Studies",
  "Analytics",
  "Animal Sciences",
  "Anthropology",
  "Applied Mathematics",
  "Applied Statistics",
  "Arabic Studies",
  "Archaeology",
  "Architectural Studies",
  "Architecture",
  "Art",
  "Art & Design",
  "Art Education",
  "Art History",
  "Art Undeclared",
  "Arts & Entertainment Technology",
  "Asian American Studies",
  "Astronomy",
  "Astronomy + Data Science",
  "Astrophysics",
  "Atmospheric Sciences",
  "Audiology",
  "Automated Trading Practices",
  "Autonomy & Robotics",
  "Balkan Studies",
  "Bilingual-Bicultural Education",
  "Biochemistry",
  "Bioengineering",
  "Bioinformatics",
  "Bioinstrumentation",
  "Biological Anthropology",
  "Biological Sciences, Teaching of",
  "Biology",
  "Biomedical Image Computing",
  "Biomolecular Engineering",
  "Biophysics & Quantitative Biology",
  "Bioprocessing & Bioenergy",
  "Brazilian Studies",
  "Building Performance",
  "Business",
  "Business + Data Science",
  "Business Administration",
  "Business Analytics",
  "Business Data Analytics",
  "Business Undeclared",
  "CPA Pathways",
  "Cancer Education Management in Underrepresented and Diverse Communities",
  "Cell & Developmental Biology",
  "Chemical & Biomolecular Engineering",
  "Chemical Engineering",
  "Chemical Engineering + Data Science",
  "Chemical Engineering Leadership",
  "Chemistry",
  "Chemistry Teaching",
  "Child Health & Well-being",
  "Choral Music",
  "Cinema Studies",
  "Civic Leadership",
  "Civil Engineering",
  "Classical Civilizations",
  "Classical Languages",
  "Classical Philology",
  "Classics",
  "Clinical and Community Nutrition",
  "Collaborative Piano",
  "College Teaching",
  "Communication",
  "Communications & Media",
  "Community Based Art Education",
  "Community Health",
  "Companion Animal & Equine Science",
  "Comparative & World Literature",
  "Comparative Biosciences",
  "Comparative Literature",
  "Compensation Best Practices",
  "Computational Science & Engineering",
  "Computing Fundamentals",
  "Construction Management",
  "Consumer Economics & Finance",
  "Consumer-Centric Innovation and Design",
  "Corporate Governance & International Business",
  "Corporate Law, Commercial Law, & Trade",
  "Costume Design & Technology",
  "Creative Lyric Theatre",
  "Creative Writing",
  "Criminal Law",
  "Criminology, Law, & Society",
  "Critical Film Production",
  "Crop & Soil Management",
  "Crop Agribusiness",
  "Crop Sciences",
  "Cultural-Linguistic Diversity",
  "Curriculum & Instruction",
  "CyberGIS and Geospatial Data Science",
  "Czech Studies",
  "Dairy Nutrition for Udder Success",
  "Dance",
  "Data Analytics in Accountancy",
  "Data Analytics in Finance",
  "Data Optimization",
  "Data Science & Engineering",
  "Design",
  "Design & Technology",
  "Design for Responsible Innovation",
  "Design of Tall Buildings",
  "Detail and Fabrication",
  "Developmental Psychopathology",
  "Dietetics",
  "Digital & Precision Agriculture",
  "Digital Agriculture",
  "Digital Learning",
  "Digital Marketing",
  "Disability Studies",
  "Diversity & Equity in Education",
  "Early Childhood Education",
  "Earth & Environmental Science",
  "Earth Science Teaching",
  "Earth, Society, & Environmental Sustainability",
  "East Asian Languages & Cultures",
  "East Asian Languages Teaching",
  "Ecological Community Psychology",
  "Ecology & Conservation Biology",
  "Ecology, Evolution & Conservation Biology",
  "Econometrics & Quantitative Economics",
  "Economics",
  "Ecosystem Stewardship & Restoration Ecology",
  "Education Policy, Organization & Leadership",
  "Educational Administration & Leadership",
  "Educational Equality & Cultural Understanding",
  "Educational Psychology",
  "Educational Technology",
  "Electrical & Computer Engineering",
  "Electrical Engineering",
  "Electronic Materials",
  "Elementary Education",
  "Energy & the Environment",
  "Engineering",
  "Engineering Mechanics",
  "Engineering Physics",
  "Engineering Technology & Management for Agricultural Systems",
  "English",
  "English Teaching",
  "English as a Second Language",
  "Enterprise Risk Management",
  "Entomology",
  "Entrepreneurship & Innovation",
  "Entrepreneurship & Strategic Innovation",
  "Environmental Chemistry",
  "Environmental Economics & Law",
  "Environmental Economics & Policy",
  "Environmental Engineering",
  "Environmental Engineering in Civil Engineering",
  "Environmental Geology",
  "Environmental Social Sciences",
  "Environmental Stewardship & Management",
  "Epidemiology, MPH",
  "European Union Studies",
  "Evolution, Ecology, and Behavior",
  "Farm Management",
  "Fashion",
  "Finance",
  "Finance + Data Science",
  "Finance in Agribusiness",
  "Financial Engineering",
  "Financial Management",
  "Financial Planning",
  "Financial Reporting & Assurance",
  "Financial and Insurance Analytics",
  "Fish, Wildlife & Conservation Biology",
  "Food & Agribusiness Management",
  "Food & Environmental Systems",
  "Food Animal Production & Management",
  "Food Regulations, Nutrition Policy, and Personalized Nutrition",
  "Food Science",
  "Food Science & Human Nutrition",
  "French",
  "French Studies",
  "French Teaching",
  "Fundamentals of Human Resources",
  "Game Development",
  "Game Studies",
  "Game Studies & Design",
  "Gender & Women's Studies",
  "Gender Relations in International Development",
  "General Bioengineering",
  "General Geography",
  "Geographic Information Science",
  "Geography",
  "Geography & Geographic Information Science",
  "Geology",
  "Geology & Geophysics",
  "Geophysics",
  "German",
  "German Business & Commercial Studies",
  "German Teaching",
  "Germanic Studies",
  "Global Challenges in Business",
  "Global Labor Studies",
  "Global Markets & Society",
  "Global Studies",
  "Global Studies in Education",
  "Graduate Preparatory (Math)",
  "Graphic Design",
  "Greek",
  "Health & Aging",
  "Health & Wellbeing",
  "Health Administration",
  "Health Behavior Change",
  "Health Behavior and Promotion",
  "Health Communication",
  "Health Diversity",
  "Health Education",
  "Health Planning & Administration",
  "Health Technology",
  "Health and Well-being for Designed Environments",
  "Heritage Studies and Preservation",
  "Higher Education",
  "Hindi Studies",
  "Hip Hop Culture and the Arts",
  "History",
  "History of Education",
  "Horticultural Food Systems",
  "Horticulture",
  "Hospitality Management",
  "Human Development & Family Studies",
  "Human Geography Concentration",
  "Human Nutrition",
  "Human Resource Development",
  "Human Resources & Industrial Relations",
  "Human Resources Data Analytics",
  "Illustration",
  "Inclusive Leadership & Learning in Organizations",
  "Inclusive by Design in Recreation, Sport, and Tourism",
  "Individual Plans of Study",
  "Industrial Design",
  "Industrial Engineering",
  "Industrial and Agricultural Safety & Health",
  "Informatics",
  "Information Management",
  "Information Sciences",
  "Information Sciences + Data Science",
  "Information Systems",
  "Information Technology & Control",
  "Innovation, Leadership, & Engineering Entrepreneurship",
  "Instructional System Design Management and Leadership",
  "Instrumental Conducting (Band)",
  "Instrumental Conducting (Orch)",
  "Instrumental Conducting (Wind Band)",
  "Instrumental Music",
  "Instrumentation and Applied Physics",
  "Integrative Biology",
  "Integrative Biology Honors",
  "Intellectual Property & Technology Law",
  "Interdisciplinary Health Sciences",
  "Interdisciplinary Practice",
  "Interdisciplinary Studies",
  "International & Comparative Law",
  "International Business",
  "International Development Economics",
  "International Education Administration and Leadership",
  "International Minor in ACES",
  "International Minor in Engineering",
  "Islamic World, Study of the",
  "Italian",
  "Japanese Arts and Aesthetics",
  "Jazz Performance",
  "Jewish Studies",
  "Journalism",
  "Justice, Democracy, & Legal Rights",
  "Kinesiology",
  "LGBT/Queer Studies",
  "Labor & Employment Relations",
  "Land, Agriculture and Alternative Investing",
  "Landscape Architecture",
  "Landscape Studies",
  "Language Studies (German)",
  "Latin",
  "Latin American & Caribbean Studies",
  "Latin American Studies",
  "Latin, Teaching of",
  "Latina/Latino Studies",
  "Law",
  "Leadership & Social Change",
  "Leadership Studies",
  "Leadership and Organizational Management",
  "Learning & Education Studies",
  "Learning Design & Leadership",
  "Learning Sciences",
  "Legal Studies",
  "Library & Information Science",
  "Lighting Design",
  "Linguistics",
  "Linguistics and Teaching English as a Second Language, BALAS (TESL)",
  "Literacy",
  "Livestock Systems Health",
  "Lyric Theatre",
  "Management",
  "Managerial Economics & Business Analysis",
  "Marketing",
  "Materials Engineering",
  "Materials Science & Engineering",
  "Materials Science & Engineering + Data Science",
  "Math Doctoral Preparation",
  "Mathematics",
  "Mathematics & Computer Science",
  "Mathematics Teaching",
  "Mathematics Teaching",
  "Mechanical Engineering",
  "Media",
  "Media & Cinema Studies",
  "Medicine",
  "Medieval Studies",
  "Mental Health Counseling",
  "Microbiology",
  "Middle Grades Education",
  "Minoritarian Aesthetics",
  "Molecular & Cellular Biology",
  "Molecular & Cellular Biology Honors",
  "Molecular & Integrative Physiology",
  "Molecular and Cellular Biology + Data Science",
  "Museum Studies",
  "Music",
  "Music Composition",
  "Music Education",
  "Music Education: Technology",
  "Music Technology",
  "Music and Sound Studies",
  "Musical Theatre",
  "Musicology",
  "Narrative",
  "Natural Resource Conservation",
  "Natural Resources & Environmental Sciences",
  "Neural Engineering",
  "Neuroscience",
  "Neuroscience of Communication",
  "New Media",
  "Nuclear, Plasma & Radiological Engineering",
  "Nuclear, Plasma, and Radiological Engineering + Data Science",
  "Nutrition",
  "Nutritional Sciences",
  "Open Studies",
  "Operations Management",
  "Organizational & Community Leadership",
  "Painting",
  "Pathobiology",
  "Performance & Literature (Music)",
  "Performance Concentration",
  "Philosophy",
  "Philosophy of Education",
  "Photography",
  "Physical Activity and Health",
  "Physical Geography",
  "Physics",
  "Physics, Teaching of",
  "Piano Pedagogy",
  "Plant Biology",
  "Plant Biotechnology",
  "Plasma Engineering",
  "Policy Economics",
  "Policy, International Trade & Development",
  "Polish Studies Concentration",
  "Political Science",
  "Portuguese",
  "Predictive Analytics and Risk Management",
  "Printmaking",
  "Production",
  "Programming",
  "Psychological Science",
  "Psychology",
  "Public Health",
  "Public Policy & Law",
  "Public Relations",
  "Queer Studies",
  "Real Estate",
  "Recreation Management",
  "Recreation, Sport & Tourism",
  "Regional Planning",
  "Regulation, Sustainability, & Compliance",
  "Rehabilitation Studies",
  "Religion",
  "Romance Linguistics",
  "Russian & East European Studies",
  "Russian Language & Literature",
  "Russian, East European & Eurasian Studies",
  "Scandinavian Studies",
  "Scenic Design",
  "Scenic Technology",
  "Schools Specialization",
  "Science",
  "Science Teaching",
  "Science of the Earth System",
  "Science, Pre-Veterinary and Medical",
  "Sculpture",
  "Second Language Acquisition & Teacher Education",
  "Secondary Education",
  "Secondary School Teaching",
  "Semiconductor Engineering",
  "Slavic Language, Literature & Culture",
  "Slavic Languages & Literatures",
  "Slavic Studies",
  "Social Science",
  "Social Science: History Teaching",
  "Social Sciences & Education Policy",
  "Social Work",
  "Society & the Environment",
  "Sociocultural & Linguistic Anthropology",
  "Sociology",
  "Sound Design & Technology",
  "South Asian & Middle Eastern Studies",
  "South Asian Studies",
  "South Slavic Studies",
  "Spanish",
  "Spanish Linguistics",
  "Spanish Literatures & Cultures",
  "Spanish Teaching",
  "Spatial & Quantitative Methods in Natural Resources & Environmental Sciences",
  "Special Education",
  "Speech & Hearing Science",
  "Speech-Language Pathology",
  "Sport Management",
  "Stage Management",
  "Statistics",
  "Statistics & Computer Science",
  "Strategic Brand Communication",
  "Strategic Leadership Management",
  "Strategy, Innovation, and Entrepreneurship",
  "Structures",
  "Studio Art",
  "Sub-Saharan African Languages",
  "Supply Chain Management",
  "Sustainability in Food & Environmental Systems",
  "Sustainability, Energy, and Environment",
  "Sustainable Design",
  "Sustainable Urban Design",
  "Systems & Entrepreneurial Engineering",
  "Systems Engineering and Design",
  "Taxation",
  "Technology & Management",
  "Technology Management",
  "Theatre",
  "Theoretical & Applied Mechanics",
  "Tourism Management",
  "Translation & Interpreting",
  "Trauma-Informed Practice and Pedagogy",
  "U.S. Legal Practice Skills",
  "Ukrainian Studies",
  "Urban Planning",
  "Urban Studies Planning",
  "Urbanism",
  "Value Chain Management",
  "Veterinary Medical Science - Comparative Biosciences",
  "Veterinary Medical Science - Pathobiology",
  "Veterinary Medical Sciences - Veterinary Clinical Medicine",
  "Veterinary Medicine",
  "Vocal Coaching & Accompanying",
  "Voice Performance",
  "Weather And Climate Risk & Analysis",
  "Wetland Science and Conservation",
  "Wildlife & Fisheries Conservation",
  "Workplace Training & Development",
  "World Literatures",
  "Writing Studies",
  "Other"
];
