export const minors = [
  "Adult Development",
  "Advertising",
  "African American Studies",
  "African Studies",
  "Aging",
  "American Indian Studies",
  "Animal Sciences",
  "Anthropology",
  "Arabic Studies",
  "Architectural Studies",
  "Art & Design",
  "Art History",
  "Asian American Studies",
  "Astronomy",
  "Atmospheric Sciences",
  "Accountancy",
  "American Indian & Indigenous Studies",
  "Bioengineering",
  "Biomolecular Engineering",
  "Business Analytics",
  "Business Minor for Non-Business Majors",
  "Balkan Studies",
  "Chemistry",
  "Child Health & Well-being",
  "Cinema Studies",
  "Civic Leadership",
  "Classical Civilizations",
  "Classical Languages",
  "Communication",
  "Community Based Art Education",
  "Computational Science & Engineering",
  "Computer Science",
  "Creative Writing",
  "Criminology, Law, & Society",
  "Critical Film Production",
  "Crop & Soil Management",
  "College Teaching",
  "Corporate Governance & International Business",
  "Dance",
  "Data Science",
  "Disability Studies",
  "Earth, Society & Environment",
  "East Asian Languages and Cultures",
  "Ecology & Conservation Biology",
  "Economics",
  "Electrical & Computer Engineering",
  "Engineering, International Minor",
  "Engineering Technology and Management for Agricultural Systems",
  "English",
  "English as a Second Language",
  "English as a Second Language, Teacher Education",
  "Environmental Economics & Law",
  "European Union Studies",
  "Food & Agribusiness Management",
  "Food & Environmental Systems",
  "Food Science",
  "French",
  "Finance",
  "Game Studies & Design",
  "Gender & Women's Studies",
  "Geography & GIS",
  "Geology",
  "German",
  "German Business & Commercial Studies Minor",
  "Global Studies",
  "Global Labor Studies",
  "Global Markets & Society",
  "Game Studies",
  "Gender Relations in International Development",
  "Health Administration",
  "Health Technology, Interdisciplinary",
  "Hindi Studies",
  "Hip Hop Culture and the Arts",
  "History",
  "Horticulture",
  "Hospitality Management",
  "Heritage Studies and Preservation",
  "Industrial and Agricultural Safety and Health",
  "Informatics",
  "Integrative Biology",
  "Interdisciplinary Minor in African American Studies",
  "Interdisciplinary Minor in African Studies",
  "Interdisciplinary Minor in Aging",
  "Interdisciplinary Minor in Asian American Studies",
  "Interdisciplinary Minor in Health Technology",
  "Interdisciplinary Minor in Jewish Culture and Society",
  "Interdisciplinary Minor in Latin American Studies",
  "Interdisciplinary Minor in Medieval Studies",
  "Interdisciplinary Minor in South Asian Studies",
  "Interdisciplinary Minor in the Study of the Islamic World",
  "International Business",
  "International Development Economics",
  "International Minor in Agricultural, Consumer, & Environmental Sciences",
  "International Minor in Engineering",
  "Islamic World, Study of the",
  "Italian",
  "Information Technology and Control",
  "Japanese Arts and Aesthetics",
  "Jewish Culture and Society",
  "Journalism",
  "Kinesiology",
  "Landscape Studies",
  "Latin American Studies",
  "Latina/Latino Studies",
  "Leadership Studies",
  "Legal Studies",
  "LGBT/Queer Studies",
  "Linguistics",
  "Latin American & Caribbean Studies",
  "Materials Science & Engineering",
  "Mathematics",
  "Mathematics: Grades 9-12, Teacher Education",
  "Media",
  "Medieval Studies",
  "Minoritarian Aesthetics",
  "Molecular & Cellular Biology",
  "Music",
  "Musical Theatre for Performing Artists",
  "Museum Studies",
  "Music and Sound Studies",
  "Natural Resource Conservation",
  "Nutrition",
  "Philosophy",
  "Physics",
  "Political Science",
  "Political & Civic Leadership",
  "Portuguese",
  "Psychology",
  "Public Health",
  "Public Relations",
  "Queer Studies",
  "Recreation, Sport & Tourism",
  "Religion",
  "Russian, East European & Eurasian Studies",
  "Russian Language & Literature",
  "Semiconductor Engineering",
  "Scandinavian Studies",
  "Slavic Language, Literature & Culture",
  "Social Work",
  "Sociology",
  "South Asian Studies, Interdisciplinary",
  "Spanish",
  "Spatial and Quantitative Methods in Natural Resources and Environmental Sciences",
  "Speech & Hearing Science",
  "Statistics",
  "Study of the Islamic World, Interdisciplinary",
  "Sub-Saharan African Languages",
  "Sustainability, Energy, and Environment Fellows Program",
  "Supply Chain Management",
  "Teacher Education Minor in English as a Second Language",
  "Teacher Education Minor in Secondary School Teaching",
  "Technology & Management",
  "Theatre",
  "Turkish Studies",
  "Translation & Interpreting Studies",
  "Urban Studies & Planning",
  "Wildlife & Fisheries Conservation",
  "World Literature"
];
